application: internet-lab
version: 0-3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /mLXMXwzDbs5BV5RS1BwSr7qY4sw.txt
  script: alexa.py

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: index.py

builtins:
- datastore_admin: on

